# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "RAW")
  end
end

lane :CD do |values|
 
    gym(scheme: 'RAW', project: "TruthOrDare.xcodeproj", clean: true, silent: true, include_bitcode: false, export_method: 'enterprise')

hockey(
	api_token: "30aafa2032474acdb26209f4e80eff06",
	ipa: "./RAW.ipa",
	notify: "1",
	notes: "Changelog"
)
 
    emails = values[:bharat.malhotra@mobileprogramming.net] ? values[:udit.madan@mobileprogramming.net] : ['[email]'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here
 
 
end
